default: &default
  adapter: postgresql
  host: localhost
  user: pg
  password: pg
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: solution_development

test:
  <<: *default
  database: solution_test
  
production:
  <<: *default
  database: solution_production
  username: solution
  password: <%= ENV['SOLUTION_DATABASE_PASSWORD'] %>
